# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UniversalTokenAssessment < Formula
  desc "Estimates Infoblox Universal DDI management tokens from cloud infrastructure"
  homepage "https://github.com/stefanriegel/Universal-Token-Assessment"
  version "3.5.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stefanriegel/Universal-Token-Assessment/releases/download/v3.5.0/universal-token-assessment_darwin_arm64.tar.gz"
      sha256 "f41531f19a259439488acbcc1217b704860999e68afe29e3ae1453e013ccb860"

      define_method(:install) do
        bin.install "universal-token-assessment"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanriegel/Universal-Token-Assessment/releases/download/v3.5.0/universal-token-assessment_linux_amd64.tar.gz"
      sha256 "ecbc359b704b3ef17d19318a6158c257cb75fa4b93317814c2deb6f27847b855"
      define_method(:install) do
        bin.install "universal-token-assessment"
      end
    end
  end
end
