# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UniversalTokenAssessment < Formula
  desc "Estimates Infoblox Universal DDI management tokens from cloud infrastructure"
  homepage "https://github.com/stefanriegel/Universal-Token-Assessment"
  version "3.10.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stefanriegel/Universal-Token-Assessment/releases/download/v3.10.0/universal-token-assessment_darwin_arm64.tar.gz"
      sha256 "8db9ae9566d0e16b21802bdd4d1fb84dd29f134abc45ac23836c9204151f87a3"

      define_method(:install) do
        bin.install "universal-token-assessment"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanriegel/Universal-Token-Assessment/releases/download/v3.10.0/universal-token-assessment_linux_amd64.tar.gz"
      sha256 "91d5cffbd5be51a4e33fb106468748c10b6d64cabdd89da6347f663becde9f8b"
      define_method(:install) do
        bin.install "universal-token-assessment"
      end
    end
  end
end
